Import Numpy

In [1]:
import numpy as np

Numpy Version

In [2]:
np.__version__

'1.21.5'

Creating Arrays from Python Lists

In [3]:
#integer array:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#upcast to floating point array:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [6]:
#explicitly specify data type usong dtype keyword:
np.array([1, 2, 3, 4, 5], dtype = 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy

In [7]:
#create a length-10 integer array filled with zeros:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [8]:
#create a length-10 floating point array filled with zeros:
np.zeros(10, dtype = np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#create a 3x4 floating point array filled with 1s:
np.ones((3,4), dtype = np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#create a 3x4 array filled with 2.1416:
np.full((3,4), 2.1416)

array([[2.1416, 2.1416, 2.1416, 2.1416],
       [2.1416, 2.1416, 2.1416, 2.1416],
       [2.1416, 2.1416, 2.1416, 2.1416]])

In [13]:
# Create an array filled with a linear sequence 
# using np.arange(start, end, step)
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
np.random.random((3, 3))

array([[0.03791088, 0.78660548, 0.10341914],
       [0.33326561, 0.96599776, 0.91053833],
       [0.44589747, 0.51386971, 0.58641007]])